### ISSUE TITLE
All UPI apps are failing 

### ISSUE THREAD

**Issue by yashwp** [drenther/upi_pay#18]
**The Problem**
No matter what UPI app I trigger, it just says, "Maximum limit exceeded...." and the transaction just got failed.
NO ERROR MESSAGE IS LOGGING

Just to cross-check I manually went to GPay & Paytm app to transfer money. It was successful.

**Comment by prince-vishal** [comment]
Yes, for me too

"Maximum limit exceeded...."

Just to cross-check I manually went to Amazon Pay & GPay app to transfer money. It was successful.

**Comment by prince-vishal** [comment]
@yashwp did you find any solution? or Alternatives?

**Comment by yashwp** [comment]
@prince-vishal Nope.

**Comment by drenther** [comment]
This issue is not related to the library. It is an issue with your merchant account ot incorrect usage of merchant code.

**Comment by prince-vishal** [comment]
UPI spec has added a sign parameter, I think you should check it

**Comment by drenther** [comment]
We are looking into it.

**Comment by drenther** [comment]
> UPI spec has added a sign parameter, I think you should check it

`sign` parameter is not something that we can add or do anything about. It is either handled by the acquiring bank or PSP app (in case of intent, which is precisely how this plugin works)

**Comment by prince-vishal** [comment]
> > UPI spec has added a sign parameter, I think you should check it
> 
> `sign` parameter is not something that we can add or do anything about. It is either handled by the acquiring bank or PSP app (in case of intent, which is precisely how this plugin works)

Yes, that's what I don't understand, the PSP app should handle it and add the sign. But I think it is not doing it when invoked using intent. They have also added a mode parameter. I played around with different mode values, but none works

**Comment by drenther** [comment]
Yes, I tried with secure intent. Assuming that's what was needed for the PSP to trigger addition of a digital signature. But it did not work as expected.

**Comment by prince-vishal** [comment]
Someone mentioned in another issue that it worked with Phonepe. I didn't get a chance to test that

**Comment by reeteshranjan** [comment]
I have tested today with my version as in the pending pull request https://github.com/drenther/upi_pay/pull/17. Things work fine for several apps (Yes Pay, BOB, iCICI, bpay, Cointabm SBI Pay tried), and some apps do not work. Google Pay and Phone Pe gave some vague security error, while other apps successfully did the payment. I am talking about payments initiated on Android through the code in this package. Be reasonable when saying "All UPI apps" are failing. It's misleading especially because you don't mention which apps are failing.

For sake of completeness of argument, my pull request modifies 2 things: 1) does not encode the VPA, and 2) adds mode=00 as per the UPI linking spec. While doing this after going through the UPI linking spec, I did notice that the merchant code and signature are values that needed to be passed; but it is not straightforward, at least for me, to get these values for individual to individual payment.

There is no pandemic going on in UPI yet, is what I can see as of today. I would give some credit to Google Pay and Phone Pe's vague errors, if they really told what the exact issue is. The real security lies at the UPI PIN onwards workflow, and not in making a software call to fill a form to do the same, which is what flutter packages like these are anyway doing. So at best one should not use such vague error giving apps and use others.

**Comment by AnandMG02** [comment]
Issue is because of MCC. You need to give correct MCC which 4 digit. If you use merchant code or id in MCC it will give error.

merchantCode: '****',

**Comment by AnandMG02** [comment]
Can someone help me with response code we are receiving. Where can we get the list of all response code ?

**Comment by drenther** [comment]
> This issue is not related to the library. It is an issue with your merchant account or incorrect usage of merchant code.

I had mentioned this previously as well.

**Comment by lzzy12** [comment]
no workaround yet?

**Comment by drenther** [comment]
There is no workaround that can be done from a plugin point of view as of now. I am keeping this issue open so that we don't have duplicate issues opened for the same.

But, we won't be replying to any more comments on status update as there is nothing to update here.

Feel free to add on if you have any findings. But as of now this thread is in "READ-ONLY" mode.

**Comment by reeteshranjan** [comment]
Please see and review https://github.com/drenther/upi_pay/pull/17

**Comment by drenther** [comment]
Closing this since #17 is merged!

**Comment by reeteshranjan** [comment]
> Can someone help me with response code we are receiving. Where can we get the list of all response code ?

Here is the doc that contains all error codes https://github.com/reeteshranjan/upi_pay/files/6338492/PHN6WKI7_UPI_Error_and_Response_Codes_V_2_3_1.pdf. Please note that these are applicable to non app-to-app workflows only; however, somehow they are flowing through the app-to-app workflows that this package implements.

**Comment by reeteshranjan** [comment]
@yashwp @lzzy12 @AnandMG02 @prince-vishal please see my comment on a related issue https://github.com/drenther/upi_pay/issues/19#issuecomment-855191757, and indicate your opinion on closing/re-opening this bug.

**Comment by reeteshranjan** [comment]
@yashwp @lzzy12 @prince-vishal please follow #38

**Comment by lzzy12** [comment]
Sorry I don't have acess to the project where this was needed anymore, can't help

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@yashwp @lzzy12 @AnandMG02
