### ISSUE TITLE
IOS Implementation

### ISSUE THREAD

**Issue by viveknimkarde** [drenther/upi_pay#2]
Any Idea of how to implement this plugin for IOS?

**Comment by drenther** [comment]
I haven't used Swift/Objective-C before. Don't have much idea. I am open to a discussion and PRs if anyone can take that up.

**Comment by pratikjain04** [comment]
@drenther Any updates on iOS front?

**Comment by drenther** [comment]
I personally don't work with iOS as of now. Would be happy to take a PR if anyone is willing to?

**Comment by reeteshranjan** [comment]
I can do iOS programming. So far did not find any documentation on an iOS mechanism similar to Android intents though.

**Comment by drenther** [comment]
https://razorpay.com/docs/payment-gateway/payment-methods/upi-intent/ios/

There is an iOS intent flow in RazorPay SDK. It doesn't look there is a spec (even roughly so like in android) for it though. Even, they seem to be supporting only three apps as of now.

Also not sure if we can emulate something similar on Flutter or not.

**Comment by reeteshranjan** [comment]
Great. I found these key custom schemes from above:

```xml
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>tez</string>
    <string>phonepe</string>
    <string>paytmmp</string>
</array>
```

Was struggling as could not find these details of the apps published anywhere e.g. comgooglemaps for Google Maps is documented by Google and was able to launch Google Maps using this custom scheme using url_launcher package's launch() call to ```comgooglemaps://``. Was trying with ```upi://``` as per the spec but no apps bothered to respond to it.

Will experiment and document.

**Comment by reeteshranjan** [comment]
All these custom schemes work and with code like this on iOS you can launch the corresponding apps. Will see if the UPI parameters work.

```dart
          final urlString = 'paytmmp://';
          final bool check = await canLaunch(urlString);
          try {
            await launch(urlString);
          } catch(error) {
            print(error.toString());
          }
```

**Comment by drenther** [comment]
Great findings, looks like we can support iOS to some extent. Any edge cases you can think of? @pepsighan @reeteshranjan

**Comment by pepsighan** [comment]
I think they should work fine for each individual app. The work will be to find custom schemes for each individual app for all to be supported. I don't have an iPhone but google pay's custom schemes are given here: https://internal-absorbed-celsius.glitch.me/. You may try if these work.

**Comment by reeteshranjan** [comment]
I found custom schemes implemented several apps using the method described here: https://www.amerhukic.com/finding-the-custom-url-scheme-of-an-ios-app.

I looked at these apps I have evaluated on Android (37) plus few more:  Airtel Pay, Amazon Pay, Axis Pay, Bandhan Bank, Baroda Pay, BHIM, BOI UPI, Cent UPI, Cointab, CORP UPI, CSB Pay, DCB UPI, Freecharge, Google Pay, ICICI Mobile, IDFC UPI, IndianBank UPI, IndusPay, KBL UPI, KVB Upay, LVB Upaay, MahaUPI, Mi Pay, Mobikwik, Oriental Pay, PayTM, Paywiz, Phone Pe, PSB, RBL UPI, SBI Pay, SyndUPI, Truecaller, UCO UPI, UltraCash, Vijaya UPI, Yes Pay

Found these apps to implement custom schemes on iOS (16): PayTM, PhonePe, Amazon, iMobile, MobiKwik, Freecharge, KVB Upay, UBI UPI, UCO UPI, Vijaya UPI, BharatPe, SyndUPI, LOTZA Pay, Airtel, BHIM, Cent UPI

These apps have `upi` as one of their custom schemes implemented: Google Pay, Mobikwik, PayTM, PhonePe, Freecharge, Lotza Pay, UBI UPI

These apps have only `upi` as their custom scheme: KVB Upay, SyndUPI, Vijaya UPI

These apps do not have `upi` scheme but some generic app name based schemes implemented: Amazon, iMobile, Airtel, BharatPe, BHIM, Cent UPI, UCO UPI

I experimented with few using `url_launcher` to see if I can get to a success payment and some kind of callback.

1.  What the URL is going to be?

At this point, at least I do not see a way to figure out what query string structure is actually expected and parsed by these apps, beyond this finding of custom schemes. Though one can guess that if UPI "listening" has been implemented by these apps, the parameters should be standard and as per the UPI specs. However; there is no clarity about the URL path e.g. is it `phonepe://upi?`, `phonepe://pay?`, `phonepe://upi/pay?` or something else. The link https://internal-absorbed-celsius.glitch.me/ shared earlier helped me with this. The logical patterns seem to be: `upi://pay?` for `upi` custom schemes, and `<non-upi-scheme>://upi/pay?` for other custom schemes. And the few apps I tried, it worked out that way.

2. Does the pre-filled payment form opens up?

It did. For Google Pay and Phone Pe.

3.  Does the payment go through?

Yes, it did go through with Google Pay.

4.  Did the callback URL work?

I put in a working URL to one of my servers as the callback URL. But it was not called.

The twist, which I discovered a bit later, is that I was testing on my iPhone 6. Most of the apps get installed but do not even proceed once they detect it's iPhone 6 (as per NPCI guidelines). I did not want to continue this research/debugging any further because I'm not sure if few apps did not respond properly due to this etc.

**Comment by reeteshranjan** [comment]
One of my ideas was that to implement a custom scheme in my app and pass a callback URL using that custom scheme (once the callback is verified to work for regular https URLs); but the UPI spec says that the callback URL must have http/https scheme. Had the URL with custom scheme worked, we would have had an experience of the whole workflow getting executed inside one's mobile, similar to how it works in Android.

At this point, not exploring any further till I get an iPhone version that is free of NCPI non-support worries.

**Comment by drenther** [comment]
Hey @reeteshranjan that is some exceptional dive deep points. Thanks for all the effort and time you have put in. I will try and explore along the same lines in  iPhone X and see if we can get anything up that will be decent enough to be packaged in a lib. But, the callback bit seems like a deal breaker so far to me.

@pepsighan it will be great if you could share your thoughts whenever you can.

**Comment by reeteshranjan** [comment]
> Hey @reeteshranjan that is some exceptional dive deep points. Thanks for all the effort and time you have put in.

Thank you @drenther! Happy to help. I love contributing to open source. Do check out my github and my organizations based repositories. Hopefully, you can find something that is useful.

**Comment by reeteshranjan** [comment]
I have captured the results of testing on iPhone 7 here:

https://docs.google.com/spreadsheets/d/1y8m2zrrhM7yZnvYJYgTUtueCatP76j6_WSJYFE6JmvQ/edit?usp=sharing

This is ongoing work. I'm stopped for today as my bank account(s) either exhausted daily transaction limits (owing to this testing 🙂) or some other issues.

Since many apps support `upi` custom scheme (and some support only that), to test each of them without any ambiguity for iOS, I offloaded all but the one I wanted to test, and then launching a URL of the form `upi://pay?pa=...` did launch the solo app.

**Comment by reeteshranjan** [comment]
Some apps demanded iOS 13.5+. All the tests have been done on iOS 14.

**Comment by reeteshranjan** [comment]
Have started a communication with Google Pay about the callback not working. Hopefully it will point an error in my integration method such as anything being wrong with value of the `url` parameter. I did try 2 versions: URL encoded and unencoded and both failed. Thinking whether they would filter out any non-www domains as some sort of additional security filtering, I did setup a www URL with a working URL call welcoming GET and POST calls. But no luck.

**Comment by reeteshranjan** [comment]
## Summary of experiments so far

### Apps researched

These apps were chosen as they supported custom schemes including/excluding `upi`: Airtel, Amazon, BHIM Cent UPI, BHIM JK Bank UPI, BHIM@SyndUPI, BHIM UCO UPI, Cointab, Freecharge, iMobile, Google Pay, Mobikwik, Paytm, Phonepe, Truecaller, WhatsApp

#### Custom Schemes

- **_Airtel_**: `myairtel`
- **_Amazon_**: `com.amazon.mobile.shopping`, `com.amazon.mobile.shopping.web`, `amazonToAlipay`, `com.amazon.mobile.sso`
- **_BHIM_** Cent UPI: `CentUPI`
- **_BHIM JK Bank UPI:_** `upi`
- **_BHIM@SyndUPI_**: `upi`
- **_BHIM UCO UPI_**: `ucoupi`
- **_Cointab_**: `upi`
- **_Freecharge_**: `upi`, `freecharge`, `com.freecharge.ios`, `freechargeapp`, `fc`
- **_iMobile_**: `ICICI`, `iMobileNative`, `icicibank`, `imobileapp`, `Imblgc`
- **_Google Pay_**: `upi`, `comgooglepaisa`, `tez`, `gpay`
- **_Mobikwik_**: `upi`, `mobikwik`
- **_Paytm_**: `upi`, `paytm`, `paytmmp`, `com.one97.paytm`
- **_PhonePe_**: `upi`, `phonepe`, `com.phonepe.PhonePeApp`
- **_Truecaller_**: `truecaller`, `truesdk`
- **_WhatsApp_**: `upi`, `whatsapp`, `whatsapp-consumer`

### Behaviour around custom schemes other than `upi`

The point of looking at these was that an app can unambiguously invoke a payment app of its user's choice. However; invoking URLs made using these custom schemes does not lead to a complete payment process. No pre-filled payment form view is shown on invocation in most cases barring few exceptions.

#### Exceptions

- _**Google Pay**_: Performs successful payments including pre-filled forms for `tez://upi/pay?` and `gpay://upi/pay?` URLs
- **_Paytm_**: Performs successful payments including pre-filled forms for `paytmmp://upi/pay?` URLs

#### Special Mentions
- **_WhatsApp_**: For `whatsapp://pay?` URLs the WhatsApp payments page gets opened

### Behaviour around `upi` custom scheme

#### Ambiguity resolution

- If there is only 1 app on iOS that implements `upi` custom scheme, it gets successfully launched
- In case of multiple apps being present, iOS choses one and it seems the one that was installed first is picked (more experiments needed to confirm). In any case, there is no way for an app to specify a choice among those installed

#### Apps that perform payment process

Few apps exhibited the following behaviour for `upi` custom scheme URLs:

- App gets launched
- Pre-filled payment form is presented
- Payment gets through successfully
- Callback url is not invoked

The apps are: **_BHIM JK Bank UPI_**, **_Cointab_**, **_Freecharge_**, **_Google Pay_**, **_Paytm_**, **_PhonePe_**, **_WhatsApp_**

#### Apps that did not respond well

- **_BHIM@SyndUPI_**, **_BHIM UCO UPI_**: No payment form is presented
- **_Mobikwik_**: It seems to have a bug where for me it keeps losing the bank accounts configured and keeps saying add them and while adding says already added and then payment does not move forward

#### Notes on behaviour around callback URL

None of the apps invoked the callback URL specified in `url` parameter.

Paytm is the one app that showed that it's trying to at least parse the URL. And it has some structural requirement on the callback URL that's not met with but it's not clearly notified by Paytm, and it gives a generic error `"ref-url invalid length"` for different values of `url` parameter.

Hacky methods of using `refUrl` (from earlier version of UPI linking spec) and `callbackUrl` (from Paytm payment API documentation) along with `url` parameter were tried; but were futile.

### Discovery implementation

![Screenshot 2020-09-25 at 10 15 26 AM](https://user-images.githubusercontent.com/5516599/94229648-bdb34b80-ff1d-11ea-826d-c5c66351f37c.png)

An app needs to specify the URL schemes it wishes to invoke in its project's `Info.plist` as shown above.

Discovery can be implemented by then calling `canOpenUrl`, as documented here https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl for each of these to see if these apps are installed. A simple tutorial here: https://useyourloaf.com/blog/querying-url-schemes-with-canopenurl/.

#### Limitations

This method does not return package bundleId of apps discovered, so while it's easy to figure out if these apps are available: **_Freecharge_**, **_Google Pay_**, **_Mobikwik_**, **_Paytm_**, **_PhonePe_**, and **_WhatsApp_**; it's impossible to figure out if these apps are the ones that implement and listen for `upi` custom scheme: **_BHIM JK Bank UPI_**, **_Cointab_**.

Hence, discovery needs to properly notify the user around this.

**Comment by reeteshranjan** [comment]
In their latest release, Jio has added support. On iOS, they have implemented custom schemes `myJio` and `prefs`. Did try it out and payment form did not open up.

**Comment by reeteshranjan** [comment]
Please see and review latest commits in #17. I have implemented the iOS support which is about discovering (as many as possible, see comments above about `upi` and other unique custom schemes) and launching any of the apps for UPI transactions.

**Comment by reeteshranjan** [comment]
See https://github.com/reeteshranjan/upi_pay/blob/master/APPS.md for latest verification status of a number of apps across android and ios.

**Comment by drenther** [comment]
closing this since #17 merged and published on pub.dev as v0.3.0

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@viveknimkarde @ngaurav
